// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: detection_api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_LaunchDetection_FullMethodName  = "/detection.api/LaunchDetection"
	Api_DisposeDetection_FullMethodName = "/detection.api/DisposeDetection"
	Api_ListDetections_FullMethodName   = "/detection.api/ListDetections"
	Api_GetDetection_FullMethodName     = "/detection.api/GetDetection"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// 检测管理服务 API（内部管理使用）
// ============================================================
type ApiClient interface {
	// 启动图像检测
	LaunchDetection(ctx context.Context, in *LaunchDetectionRequest, opts ...grpc.CallOption) (*LaunchDetectionResponse, error)
	// 停止图像检测
	DisposeDetection(ctx context.Context, in *DisposeDetectionRequest, opts ...grpc.CallOption) (*DisposeDetectionResponse, error)
	// 列出所有检测配置
	ListDetections(ctx context.Context, in *ListDetectionsRequest, opts ...grpc.CallOption) (*ListDetectionsResponse, error)
	// 获取单个检测配置
	GetDetection(ctx context.Context, in *GetDetectionRequest, opts ...grpc.CallOption) (*GetDetectionResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) LaunchDetection(ctx context.Context, in *LaunchDetectionRequest, opts ...grpc.CallOption) (*LaunchDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchDetectionResponse)
	err := c.cc.Invoke(ctx, Api_LaunchDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DisposeDetection(ctx context.Context, in *DisposeDetectionRequest, opts ...grpc.CallOption) (*DisposeDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisposeDetectionResponse)
	err := c.cc.Invoke(ctx, Api_DisposeDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListDetections(ctx context.Context, in *ListDetectionsRequest, opts ...grpc.CallOption) (*ListDetectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDetectionsResponse)
	err := c.cc.Invoke(ctx, Api_ListDetections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetDetection(ctx context.Context, in *GetDetectionRequest, opts ...grpc.CallOption) (*GetDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetectionResponse)
	err := c.cc.Invoke(ctx, Api_GetDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
//
// ============================================================
// 检测管理服务 API（内部管理使用）
// ============================================================
type ApiServer interface {
	// 启动图像检测
	LaunchDetection(context.Context, *LaunchDetectionRequest) (*LaunchDetectionResponse, error)
	// 停止图像检测
	DisposeDetection(context.Context, *DisposeDetectionRequest) (*DisposeDetectionResponse, error)
	// 列出所有检测配置
	ListDetections(context.Context, *ListDetectionsRequest) (*ListDetectionsResponse, error)
	// 获取单个检测配置
	GetDetection(context.Context, *GetDetectionRequest) (*GetDetectionResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) LaunchDetection(context.Context, *LaunchDetectionRequest) (*LaunchDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchDetection not implemented")
}
func (UnimplementedApiServer) DisposeDetection(context.Context, *DisposeDetectionRequest) (*DisposeDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisposeDetection not implemented")
}
func (UnimplementedApiServer) ListDetections(context.Context, *ListDetectionsRequest) (*ListDetectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDetections not implemented")
}
func (UnimplementedApiServer) GetDetection(context.Context, *GetDetectionRequest) (*GetDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetection not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_LaunchDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).LaunchDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_LaunchDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).LaunchDetection(ctx, req.(*LaunchDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DisposeDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisposeDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DisposeDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DisposeDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DisposeDetection(ctx, req.(*DisposeDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListDetections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDetectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListDetections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ListDetections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListDetections(ctx, req.(*ListDetectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetDetection(ctx, req.(*GetDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detection.api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchDetection",
			Handler:    _Api_LaunchDetection_Handler,
		},
		{
			MethodName: "DisposeDetection",
			Handler:    _Api_DisposeDetection_Handler,
		},
		{
			MethodName: "ListDetections",
			Handler:    _Api_ListDetections_Handler,
		},
		{
			MethodName: "GetDetection",
			Handler:    _Api_GetDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detection_api.proto",
}
