// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 同步流请求
type SyncStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamInfo          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	FullSync      bool                   `protobuf:"varint,2,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`   // 是否为全量同步
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp in milliseconds
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // 发送节点ID
	AuthToken     string                 `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // 授权令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStreamsRequest) Reset() {
	*x = SyncStreamsRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStreamsRequest) ProtoMessage() {}

func (x *SyncStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStreamsRequest.ProtoReflect.Descriptor instead.
func (*SyncStreamsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *SyncStreamsRequest) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *SyncStreamsRequest) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

func (x *SyncStreamsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SyncStreamsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncStreamsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 同步流响应数据
type SyncStreamsResponseData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount   int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`      // 成功接受的流数量
	RejectedCount   int32                  `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`      // 被拒绝的流数量
	RejectedStreams []string               `protobuf:"bytes,3,rep,name=rejected_streams,json=rejectedStreams,proto3" json:"rejected_streams,omitempty"` // 被拒绝的流路径
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // Unix timestamp in milliseconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncStreamsResponseData) Reset() {
	*x = SyncStreamsResponseData{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStreamsResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStreamsResponseData) ProtoMessage() {}

func (x *SyncStreamsResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStreamsResponseData.ProtoReflect.Descriptor instead.
func (*SyncStreamsResponseData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStreamsResponseData) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *SyncStreamsResponseData) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *SyncStreamsResponseData) GetRejectedStreams() []string {
	if x != nil {
		return x.RejectedStreams
	}
	return nil
}

func (x *SyncStreamsResponseData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 同步流响应
type SyncStreamsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SyncStreamsResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStreamsResponse) Reset() {
	*x = SyncStreamsResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStreamsResponse) ProtoMessage() {}

func (x *SyncStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStreamsResponse.ProtoReflect.Descriptor instead.
func (*SyncStreamsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *SyncStreamsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncStreamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncStreamsResponse) GetData() *SyncStreamsResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除流请求
type RemoveStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp in milliseconds
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // 发送节点ID
	AuthToken     string                 `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // 授权令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStreamRequest) Reset() {
	*x = RemoveStreamRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStreamRequest) ProtoMessage() {}

func (x *RemoveStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStreamRequest.ProtoReflect.Descriptor instead.
func (*RemoveStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveStreamRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *RemoveStreamRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RemoveStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RemoveStreamRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 删除流响应数据
type RemoveStreamResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`     // 是否成功移除
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStreamResponseData) Reset() {
	*x = RemoveStreamResponseData{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStreamResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStreamResponseData) ProtoMessage() {}

func (x *RemoveStreamResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStreamResponseData.ProtoReflect.Descriptor instead.
func (*RemoveStreamResponseData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveStreamResponseData) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *RemoveStreamResponseData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 删除流响应
type RemoveStreamResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          int32                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RemoveStreamResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStreamResponse) Reset() {
	*x = RemoveStreamResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStreamResponse) ProtoMessage() {}

func (x *RemoveStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStreamResponse.ProtoReflect.Descriptor instead.
func (*RemoveStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveStreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveStreamResponse) GetData() *RemoveStreamResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求全量同步请求
type RequestFullSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // 请求节点ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp in milliseconds
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // 授权令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFullSyncRequest) Reset() {
	*x = RequestFullSyncRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFullSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFullSyncRequest) ProtoMessage() {}

func (x *RequestFullSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFullSyncRequest.ProtoReflect.Descriptor instead.
func (*RequestFullSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *RequestFullSyncRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RequestFullSyncRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestFullSyncRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 请求全量同步响应数据
type RequestFullSyncResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`           // 是否接受同步请求
	SyncId        int64                  `protobuf:"varint,2,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"` // 同步ID
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFullSyncResponseData) Reset() {
	*x = RequestFullSyncResponseData{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFullSyncResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFullSyncResponseData) ProtoMessage() {}

func (x *RequestFullSyncResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFullSyncResponseData.ProtoReflect.Descriptor instead.
func (*RequestFullSyncResponseData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *RequestFullSyncResponseData) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RequestFullSyncResponseData) GetSyncId() int64 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *RequestFullSyncResponseData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 请求全量同步响应
type RequestFullSyncResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RequestFullSyncResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFullSyncResponse) Reset() {
	*x = RequestFullSyncResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFullSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFullSyncResponse) ProtoMessage() {}

func (x *RequestFullSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFullSyncResponse.ProtoReflect.Descriptor instead.
func (*RequestFullSyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *RequestFullSyncResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RequestFullSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestFullSyncResponse) GetData() *RequestFullSyncResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\x1a\rcluster.proto\x1a\n" +
	"node.proto\x1a\fstream.proto\"\xb1\x01\n" +
	"\x12SyncStreamsRequest\x12(\n" +
	"\astreams\x18\x01 \x03(\v2\x0e.pb.StreamInfoR\astreams\x12\x1b\n" +
	"\tfull_sync\x18\x02 \x01(\bR\bfullSync\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\"\xb0\x01\n" +
	"\x17SyncStreamsResponseData\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x05R\rrejectedCount\x12)\n" +
	"\x10rejected_streams\x18\x03 \x03(\tR\x0frejectedStreams\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"t\n" +
	"\x13SyncStreamsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.pb.SyncStreamsResponseDataR\x04data\"\x8c\x01\n" +
	"\x13RemoveStreamRequest\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\"R\n" +
	"\x18RemoveStreamResponseData\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"v\n" +
	"\x14RemoveStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1c.pb.RemoveStreamResponseDataR\x04data\"n\n" +
	"\x16RequestFullSyncRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"p\n" +
	"\x1bRequestFullSyncResponseData\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\async_id\x18\x02 \x01(\x03R\x06syncId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"|\n" +
	"\x17RequestFullSyncResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.pb.RequestFullSyncResponseDataR\x04data2\xdb\x11\n" +
	"\x03Api\x12j\n" +
	"\x10GetClusterStatus\x12\x1b.pb.GetClusterStatusRequest\x1a\x1c.pb.GetClusterStatusResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/cluster/api/status\x12Q\n" +
	"\bGetNodes\x12\x13.pb.GetNodesRequest\x1a\x14.pb.GetNodesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/cluster/api/nodes\x12[\n" +
	"\vHealthCheck\x12\x16.pb.HealthCheckRequest\x1a\x17.pb.HealthCheckResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/cluster/api/health\x12\x82\x01\n" +
	"\x10UpdateNodeConfig\x12\x1b.pb.UpdateNodeConfigRequest\x1a\x1c.pb.UpdateNodeConfigResponse\"3\x82\xd3\xe4\x93\x02-:\x06config\x1a#/cluster/api/nodes/{node_id}/config\x12v\n" +
	"\x11GetClusterMetrics\x12\x1c.pb.GetClusterMetricsRequest\x1a\x1d.pb.GetClusterMetricsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/cluster/api/cluster/metrics\x12r\n" +
	"\x10GetClusterConfig\x12\x1b.pb.GetClusterConfigRequest\x1a\x1c.pb.GetClusterConfigResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/cluster/api/cluster/config\x12\x83\x01\n" +
	"\x13UpdateClusterConfig\x12\x1e.pb.UpdateClusterConfigRequest\x1a\x1f.pb.UpdateClusterConfigResponse\"+\x82\xd3\xe4\x93\x02%:\x06config\x1a\x1b/cluster/api/cluster/config\x12o\n" +
	"\rSendHeartbeat\x12\x14.pb.HeartbeatRequest\x1a\x15.pb.HeartbeatResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/cluster/api/nodes/{node_id}/heartbeat\x12d\n" +
	"\vGetNodeInfo\x12\x16.pb.GetNodeInfoRequest\x1a\x17.pb.GetNodeInfoResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/cluster/api/nodes/{node_id}\x12r\n" +
	"\x0eRegisterStream\x12\x19.pb.RegisterStreamRequest\x1a\x1a.pb.RegisterStreamResponse\")\x82\xd3\xe4\x93\x02#:\vstream_info\"\x14/cluster/api/streams\x12y\n" +
	"\x10UnregisterStream\x12\x1b.pb.UnregisterStreamRequest\x1a\x1c.pb.UnregisterStreamResponse\"*\x82\xd3\xe4\x93\x02$*\"/cluster/api/streams/{stream_path}\x12p\n" +
	"\rGetStreamInfo\x12\x18.pb.GetStreamInfoRequest\x1a\x19.pb.GetStreamInfoResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/cluster/api/streams/{stream_path}\x12n\n" +
	"\x11GetClusterStreams\x12\x1c.pb.GetClusterStreamsRequest\x1a\x1d.pb.GetClusterStreamsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/cluster/api/streams\x12\x99\x01\n" +
	"\x1aGetOptimalNodeForPublisher\x12%.pb.GetOptimalNodeForPublisherRequest\x1a&.pb.GetOptimalNodeForPublisherResponse\",\x82\xd3\xe4\x93\x02&\x12$/cluster/api/nodes/optimal/publisher\x12\xab\x01\n" +
	"\x1bGetOptimalNodeForSubscriber\x12&.pb.GetOptimalNodeForSubscriberRequest\x1a'.pb.GetOptimalNodeForSubscriberResponse\";\x82\xd3\xe4\x93\x025\x123/cluster/api/nodes/optimal/subscriber/{stream_path}\x12\x85\x01\n" +
	"\x11UpdateStreamState\x12\x1c.pb.UpdateStreamStateRequest\x1a\x1d.pb.UpdateStreamStateResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\x1a(/cluster/api/streams/{stream_path}/state\x12d\n" +
	"\vSyncStreams\x12\x16.pb.SyncStreamsRequest\x1a\x17.pb.SyncStreamsResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/cluster/api/sync/streams\x12r\n" +
	"\fRemoveStream\x12\x17.pb.RemoveStreamRequest\x1a\x18.pb.RemoveStreamResponse\"/\x82\xd3\xe4\x93\x02)*'/cluster/api/sync/streams/{stream_path}\x12m\n" +
	"\x0fRequestFullSync\x12\x1a.pb.RequestFullSyncRequest\x1a\x1b.pb.RequestFullSyncResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/cluster/api/sync/fullB\x1fZ\x1dm7s.live/v5/plugin/cluster/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_goTypes = []any{
	(*SyncStreamsRequest)(nil),                  // 0: pb.SyncStreamsRequest
	(*SyncStreamsResponseData)(nil),             // 1: pb.SyncStreamsResponseData
	(*SyncStreamsResponse)(nil),                 // 2: pb.SyncStreamsResponse
	(*RemoveStreamRequest)(nil),                 // 3: pb.RemoveStreamRequest
	(*RemoveStreamResponseData)(nil),            // 4: pb.RemoveStreamResponseData
	(*RemoveStreamResponse)(nil),                // 5: pb.RemoveStreamResponse
	(*RequestFullSyncRequest)(nil),              // 6: pb.RequestFullSyncRequest
	(*RequestFullSyncResponseData)(nil),         // 7: pb.RequestFullSyncResponseData
	(*RequestFullSyncResponse)(nil),             // 8: pb.RequestFullSyncResponse
	(*StreamInfo)(nil),                          // 9: pb.StreamInfo
	(*GetClusterStatusRequest)(nil),             // 10: pb.GetClusterStatusRequest
	(*GetNodesRequest)(nil),                     // 11: pb.GetNodesRequest
	(*HealthCheckRequest)(nil),                  // 12: pb.HealthCheckRequest
	(*UpdateNodeConfigRequest)(nil),             // 13: pb.UpdateNodeConfigRequest
	(*GetClusterMetricsRequest)(nil),            // 14: pb.GetClusterMetricsRequest
	(*GetClusterConfigRequest)(nil),             // 15: pb.GetClusterConfigRequest
	(*UpdateClusterConfigRequest)(nil),          // 16: pb.UpdateClusterConfigRequest
	(*HeartbeatRequest)(nil),                    // 17: pb.HeartbeatRequest
	(*GetNodeInfoRequest)(nil),                  // 18: pb.GetNodeInfoRequest
	(*RegisterStreamRequest)(nil),               // 19: pb.RegisterStreamRequest
	(*UnregisterStreamRequest)(nil),             // 20: pb.UnregisterStreamRequest
	(*GetStreamInfoRequest)(nil),                // 21: pb.GetStreamInfoRequest
	(*GetClusterStreamsRequest)(nil),            // 22: pb.GetClusterStreamsRequest
	(*GetOptimalNodeForPublisherRequest)(nil),   // 23: pb.GetOptimalNodeForPublisherRequest
	(*GetOptimalNodeForSubscriberRequest)(nil),  // 24: pb.GetOptimalNodeForSubscriberRequest
	(*UpdateStreamStateRequest)(nil),            // 25: pb.UpdateStreamStateRequest
	(*GetClusterStatusResponse)(nil),            // 26: pb.GetClusterStatusResponse
	(*GetNodesResponse)(nil),                    // 27: pb.GetNodesResponse
	(*HealthCheckResponse)(nil),                 // 28: pb.HealthCheckResponse
	(*UpdateNodeConfigResponse)(nil),            // 29: pb.UpdateNodeConfigResponse
	(*GetClusterMetricsResponse)(nil),           // 30: pb.GetClusterMetricsResponse
	(*GetClusterConfigResponse)(nil),            // 31: pb.GetClusterConfigResponse
	(*UpdateClusterConfigResponse)(nil),         // 32: pb.UpdateClusterConfigResponse
	(*HeartbeatResponse)(nil),                   // 33: pb.HeartbeatResponse
	(*GetNodeInfoResponse)(nil),                 // 34: pb.GetNodeInfoResponse
	(*RegisterStreamResponse)(nil),              // 35: pb.RegisterStreamResponse
	(*UnregisterStreamResponse)(nil),            // 36: pb.UnregisterStreamResponse
	(*GetStreamInfoResponse)(nil),               // 37: pb.GetStreamInfoResponse
	(*GetClusterStreamsResponse)(nil),           // 38: pb.GetClusterStreamsResponse
	(*GetOptimalNodeForPublisherResponse)(nil),  // 39: pb.GetOptimalNodeForPublisherResponse
	(*GetOptimalNodeForSubscriberResponse)(nil), // 40: pb.GetOptimalNodeForSubscriberResponse
	(*UpdateStreamStateResponse)(nil),           // 41: pb.UpdateStreamStateResponse
}
var file_api_proto_depIdxs = []int32{
	9,  // 0: pb.SyncStreamsRequest.streams:type_name -> pb.StreamInfo
	1,  // 1: pb.SyncStreamsResponse.data:type_name -> pb.SyncStreamsResponseData
	4,  // 2: pb.RemoveStreamResponse.data:type_name -> pb.RemoveStreamResponseData
	7,  // 3: pb.RequestFullSyncResponse.data:type_name -> pb.RequestFullSyncResponseData
	10, // 4: pb.Api.GetClusterStatus:input_type -> pb.GetClusterStatusRequest
	11, // 5: pb.Api.GetNodes:input_type -> pb.GetNodesRequest
	12, // 6: pb.Api.HealthCheck:input_type -> pb.HealthCheckRequest
	13, // 7: pb.Api.UpdateNodeConfig:input_type -> pb.UpdateNodeConfigRequest
	14, // 8: pb.Api.GetClusterMetrics:input_type -> pb.GetClusterMetricsRequest
	15, // 9: pb.Api.GetClusterConfig:input_type -> pb.GetClusterConfigRequest
	16, // 10: pb.Api.UpdateClusterConfig:input_type -> pb.UpdateClusterConfigRequest
	17, // 11: pb.Api.SendHeartbeat:input_type -> pb.HeartbeatRequest
	18, // 12: pb.Api.GetNodeInfo:input_type -> pb.GetNodeInfoRequest
	19, // 13: pb.Api.RegisterStream:input_type -> pb.RegisterStreamRequest
	20, // 14: pb.Api.UnregisterStream:input_type -> pb.UnregisterStreamRequest
	21, // 15: pb.Api.GetStreamInfo:input_type -> pb.GetStreamInfoRequest
	22, // 16: pb.Api.GetClusterStreams:input_type -> pb.GetClusterStreamsRequest
	23, // 17: pb.Api.GetOptimalNodeForPublisher:input_type -> pb.GetOptimalNodeForPublisherRequest
	24, // 18: pb.Api.GetOptimalNodeForSubscriber:input_type -> pb.GetOptimalNodeForSubscriberRequest
	25, // 19: pb.Api.UpdateStreamState:input_type -> pb.UpdateStreamStateRequest
	0,  // 20: pb.Api.SyncStreams:input_type -> pb.SyncStreamsRequest
	3,  // 21: pb.Api.RemoveStream:input_type -> pb.RemoveStreamRequest
	6,  // 22: pb.Api.RequestFullSync:input_type -> pb.RequestFullSyncRequest
	26, // 23: pb.Api.GetClusterStatus:output_type -> pb.GetClusterStatusResponse
	27, // 24: pb.Api.GetNodes:output_type -> pb.GetNodesResponse
	28, // 25: pb.Api.HealthCheck:output_type -> pb.HealthCheckResponse
	29, // 26: pb.Api.UpdateNodeConfig:output_type -> pb.UpdateNodeConfigResponse
	30, // 27: pb.Api.GetClusterMetrics:output_type -> pb.GetClusterMetricsResponse
	31, // 28: pb.Api.GetClusterConfig:output_type -> pb.GetClusterConfigResponse
	32, // 29: pb.Api.UpdateClusterConfig:output_type -> pb.UpdateClusterConfigResponse
	33, // 30: pb.Api.SendHeartbeat:output_type -> pb.HeartbeatResponse
	34, // 31: pb.Api.GetNodeInfo:output_type -> pb.GetNodeInfoResponse
	35, // 32: pb.Api.RegisterStream:output_type -> pb.RegisterStreamResponse
	36, // 33: pb.Api.UnregisterStream:output_type -> pb.UnregisterStreamResponse
	37, // 34: pb.Api.GetStreamInfo:output_type -> pb.GetStreamInfoResponse
	38, // 35: pb.Api.GetClusterStreams:output_type -> pb.GetClusterStreamsResponse
	39, // 36: pb.Api.GetOptimalNodeForPublisher:output_type -> pb.GetOptimalNodeForPublisherResponse
	40, // 37: pb.Api.GetOptimalNodeForSubscriber:output_type -> pb.GetOptimalNodeForSubscriberResponse
	41, // 38: pb.Api.UpdateStreamState:output_type -> pb.UpdateStreamStateResponse
	2,  // 39: pb.Api.SyncStreams:output_type -> pb.SyncStreamsResponse
	5,  // 40: pb.Api.RemoveStream:output_type -> pb.RemoveStreamResponse
	8,  // 41: pb.Api.RequestFullSync:output_type -> pb.RequestFullSyncResponse
	23, // [23:42] is the sub-list for method output_type
	4,  // [4:23] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_common_proto_init()
	file_cluster_proto_init()
	file_node_proto_init()
	file_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
