// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_GetClusterStatus_FullMethodName            = "/pb.Api/GetClusterStatus"
	Api_GetNodes_FullMethodName                    = "/pb.Api/GetNodes"
	Api_HealthCheck_FullMethodName                 = "/pb.Api/HealthCheck"
	Api_UpdateNodeConfig_FullMethodName            = "/pb.Api/UpdateNodeConfig"
	Api_GetClusterMetrics_FullMethodName           = "/pb.Api/GetClusterMetrics"
	Api_GetClusterConfig_FullMethodName            = "/pb.Api/GetClusterConfig"
	Api_UpdateClusterConfig_FullMethodName         = "/pb.Api/UpdateClusterConfig"
	Api_SendHeartbeat_FullMethodName               = "/pb.Api/SendHeartbeat"
	Api_GetNodeInfo_FullMethodName                 = "/pb.Api/GetNodeInfo"
	Api_RegisterStream_FullMethodName              = "/pb.Api/RegisterStream"
	Api_UnregisterStream_FullMethodName            = "/pb.Api/UnregisterStream"
	Api_GetStreamInfo_FullMethodName               = "/pb.Api/GetStreamInfo"
	Api_GetClusterStreams_FullMethodName           = "/pb.Api/GetClusterStreams"
	Api_GetOptimalNodeForPublisher_FullMethodName  = "/pb.Api/GetOptimalNodeForPublisher"
	Api_GetOptimalNodeForSubscriber_FullMethodName = "/pb.Api/GetOptimalNodeForSubscriber"
	Api_UpdateStreamState_FullMethodName           = "/pb.Api/UpdateStreamState"
	Api_SyncStreams_FullMethodName                 = "/pb.Api/SyncStreams"
	Api_RemoveStream_FullMethodName                = "/pb.Api/RemoveStream"
	Api_RequestFullSync_FullMethodName             = "/pb.Api/RequestFullSync"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API 服务
type ApiClient interface {
	// 集群管理接口
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*UpdateNodeConfigResponse, error)
	GetClusterMetrics(ctx context.Context, in *GetClusterMetricsRequest, opts ...grpc.CallOption) (*GetClusterMetricsResponse, error)
	GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*GetClusterConfigResponse, error)
	UpdateClusterConfig(ctx context.Context, in *UpdateClusterConfigRequest, opts ...grpc.CallOption) (*UpdateClusterConfigResponse, error)
	// 节点管理接口
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	// 流管理接口
	RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*RegisterStreamResponse, error)
	UnregisterStream(ctx context.Context, in *UnregisterStreamRequest, opts ...grpc.CallOption) (*UnregisterStreamResponse, error)
	GetStreamInfo(ctx context.Context, in *GetStreamInfoRequest, opts ...grpc.CallOption) (*GetStreamInfoResponse, error)
	GetClusterStreams(ctx context.Context, in *GetClusterStreamsRequest, opts ...grpc.CallOption) (*GetClusterStreamsResponse, error)
	GetOptimalNodeForPublisher(ctx context.Context, in *GetOptimalNodeForPublisherRequest, opts ...grpc.CallOption) (*GetOptimalNodeForPublisherResponse, error)
	GetOptimalNodeForSubscriber(ctx context.Context, in *GetOptimalNodeForSubscriberRequest, opts ...grpc.CallOption) (*GetOptimalNodeForSubscriberResponse, error)
	UpdateStreamState(ctx context.Context, in *UpdateStreamStateRequest, opts ...grpc.CallOption) (*UpdateStreamStateResponse, error)
	// 流同步服务接口
	SyncStreams(ctx context.Context, in *SyncStreamsRequest, opts ...grpc.CallOption) (*SyncStreamsResponse, error)
	RemoveStream(ctx context.Context, in *RemoveStreamRequest, opts ...grpc.CallOption) (*RemoveStreamResponse, error)
	RequestFullSync(ctx context.Context, in *RequestFullSyncRequest, opts ...grpc.CallOption) (*RequestFullSyncResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, Api_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, Api_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Api_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*UpdateNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeConfigResponse)
	err := c.cc.Invoke(ctx, Api_UpdateNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetClusterMetrics(ctx context.Context, in *GetClusterMetricsRequest, opts ...grpc.CallOption) (*GetClusterMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterMetricsResponse)
	err := c.cc.Invoke(ctx, Api_GetClusterMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*GetClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterConfigResponse)
	err := c.cc.Invoke(ctx, Api_GetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateClusterConfig(ctx context.Context, in *UpdateClusterConfigRequest, opts ...grpc.CallOption) (*UpdateClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClusterConfigResponse)
	err := c.cc.Invoke(ctx, Api_UpdateClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Api_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, Api_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*RegisterStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterStreamResponse)
	err := c.cc.Invoke(ctx, Api_RegisterStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UnregisterStream(ctx context.Context, in *UnregisterStreamRequest, opts ...grpc.CallOption) (*UnregisterStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterStreamResponse)
	err := c.cc.Invoke(ctx, Api_UnregisterStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetStreamInfo(ctx context.Context, in *GetStreamInfoRequest, opts ...grpc.CallOption) (*GetStreamInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamInfoResponse)
	err := c.cc.Invoke(ctx, Api_GetStreamInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetClusterStreams(ctx context.Context, in *GetClusterStreamsRequest, opts ...grpc.CallOption) (*GetClusterStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStreamsResponse)
	err := c.cc.Invoke(ctx, Api_GetClusterStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetOptimalNodeForPublisher(ctx context.Context, in *GetOptimalNodeForPublisherRequest, opts ...grpc.CallOption) (*GetOptimalNodeForPublisherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOptimalNodeForPublisherResponse)
	err := c.cc.Invoke(ctx, Api_GetOptimalNodeForPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetOptimalNodeForSubscriber(ctx context.Context, in *GetOptimalNodeForSubscriberRequest, opts ...grpc.CallOption) (*GetOptimalNodeForSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOptimalNodeForSubscriberResponse)
	err := c.cc.Invoke(ctx, Api_GetOptimalNodeForSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateStreamState(ctx context.Context, in *UpdateStreamStateRequest, opts ...grpc.CallOption) (*UpdateStreamStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStreamStateResponse)
	err := c.cc.Invoke(ctx, Api_UpdateStreamState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SyncStreams(ctx context.Context, in *SyncStreamsRequest, opts ...grpc.CallOption) (*SyncStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStreamsResponse)
	err := c.cc.Invoke(ctx, Api_SyncStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RemoveStream(ctx context.Context, in *RemoveStreamRequest, opts ...grpc.CallOption) (*RemoveStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStreamResponse)
	err := c.cc.Invoke(ctx, Api_RemoveStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RequestFullSync(ctx context.Context, in *RequestFullSyncRequest, opts ...grpc.CallOption) (*RequestFullSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestFullSyncResponse)
	err := c.cc.Invoke(ctx, Api_RequestFullSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
//
// API 服务
type ApiServer interface {
	// 集群管理接口
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*UpdateNodeConfigResponse, error)
	GetClusterMetrics(context.Context, *GetClusterMetricsRequest) (*GetClusterMetricsResponse, error)
	GetClusterConfig(context.Context, *GetClusterConfigRequest) (*GetClusterConfigResponse, error)
	UpdateClusterConfig(context.Context, *UpdateClusterConfigRequest) (*UpdateClusterConfigResponse, error)
	// 节点管理接口
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	// 流管理接口
	RegisterStream(context.Context, *RegisterStreamRequest) (*RegisterStreamResponse, error)
	UnregisterStream(context.Context, *UnregisterStreamRequest) (*UnregisterStreamResponse, error)
	GetStreamInfo(context.Context, *GetStreamInfoRequest) (*GetStreamInfoResponse, error)
	GetClusterStreams(context.Context, *GetClusterStreamsRequest) (*GetClusterStreamsResponse, error)
	GetOptimalNodeForPublisher(context.Context, *GetOptimalNodeForPublisherRequest) (*GetOptimalNodeForPublisherResponse, error)
	GetOptimalNodeForSubscriber(context.Context, *GetOptimalNodeForSubscriberRequest) (*GetOptimalNodeForSubscriberResponse, error)
	UpdateStreamState(context.Context, *UpdateStreamStateRequest) (*UpdateStreamStateResponse, error)
	// 流同步服务接口
	SyncStreams(context.Context, *SyncStreamsRequest) (*SyncStreamsResponse, error)
	RemoveStream(context.Context, *RemoveStreamRequest) (*RemoveStreamResponse, error)
	RequestFullSync(context.Context, *RequestFullSyncRequest) (*RequestFullSyncResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedApiServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedApiServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedApiServer) UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*UpdateNodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeConfig not implemented")
}
func (UnimplementedApiServer) GetClusterMetrics(context.Context, *GetClusterMetricsRequest) (*GetClusterMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterMetrics not implemented")
}
func (UnimplementedApiServer) GetClusterConfig(context.Context, *GetClusterConfigRequest) (*GetClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterConfig not implemented")
}
func (UnimplementedApiServer) UpdateClusterConfig(context.Context, *UpdateClusterConfigRequest) (*UpdateClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClusterConfig not implemented")
}
func (UnimplementedApiServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedApiServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedApiServer) RegisterStream(context.Context, *RegisterStreamRequest) (*RegisterStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStream not implemented")
}
func (UnimplementedApiServer) UnregisterStream(context.Context, *UnregisterStreamRequest) (*UnregisterStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterStream not implemented")
}
func (UnimplementedApiServer) GetStreamInfo(context.Context, *GetStreamInfoRequest) (*GetStreamInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamInfo not implemented")
}
func (UnimplementedApiServer) GetClusterStreams(context.Context, *GetClusterStreamsRequest) (*GetClusterStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStreams not implemented")
}
func (UnimplementedApiServer) GetOptimalNodeForPublisher(context.Context, *GetOptimalNodeForPublisherRequest) (*GetOptimalNodeForPublisherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptimalNodeForPublisher not implemented")
}
func (UnimplementedApiServer) GetOptimalNodeForSubscriber(context.Context, *GetOptimalNodeForSubscriberRequest) (*GetOptimalNodeForSubscriberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptimalNodeForSubscriber not implemented")
}
func (UnimplementedApiServer) UpdateStreamState(context.Context, *UpdateStreamStateRequest) (*UpdateStreamStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStreamState not implemented")
}
func (UnimplementedApiServer) SyncStreams(context.Context, *SyncStreamsRequest) (*SyncStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncStreams not implemented")
}
func (UnimplementedApiServer) RemoveStream(context.Context, *RemoveStreamRequest) (*RemoveStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveStream not implemented")
}
func (UnimplementedApiServer) RequestFullSync(context.Context, *RequestFullSyncRequest) (*RequestFullSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestFullSync not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateNodeConfig(ctx, req.(*UpdateNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetClusterMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetClusterMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetClusterMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetClusterMetrics(ctx, req.(*GetClusterMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetClusterConfig(ctx, req.(*GetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateClusterConfig(ctx, req.(*UpdateClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RegisterStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RegisterStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RegisterStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RegisterStream(ctx, req.(*RegisterStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UnregisterStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UnregisterStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UnregisterStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UnregisterStream(ctx, req.(*UnregisterStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetStreamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetStreamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetStreamInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetStreamInfo(ctx, req.(*GetStreamInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetClusterStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetClusterStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetClusterStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetClusterStreams(ctx, req.(*GetClusterStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetOptimalNodeForPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptimalNodeForPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetOptimalNodeForPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetOptimalNodeForPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetOptimalNodeForPublisher(ctx, req.(*GetOptimalNodeForPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetOptimalNodeForSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptimalNodeForSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetOptimalNodeForSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetOptimalNodeForSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetOptimalNodeForSubscriber(ctx, req.(*GetOptimalNodeForSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateStreamState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateStreamState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateStreamState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateStreamState(ctx, req.(*UpdateStreamStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SyncStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SyncStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_SyncStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SyncStreams(ctx, req.(*SyncStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RemoveStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RemoveStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RemoveStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RemoveStream(ctx, req.(*RemoveStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RequestFullSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFullSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestFullSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RequestFullSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestFullSync(ctx, req.(*RequestFullSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStatus",
			Handler:    _Api_GetClusterStatus_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _Api_GetNodes_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Api_HealthCheck_Handler,
		},
		{
			MethodName: "UpdateNodeConfig",
			Handler:    _Api_UpdateNodeConfig_Handler,
		},
		{
			MethodName: "GetClusterMetrics",
			Handler:    _Api_GetClusterMetrics_Handler,
		},
		{
			MethodName: "GetClusterConfig",
			Handler:    _Api_GetClusterConfig_Handler,
		},
		{
			MethodName: "UpdateClusterConfig",
			Handler:    _Api_UpdateClusterConfig_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _Api_SendHeartbeat_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _Api_GetNodeInfo_Handler,
		},
		{
			MethodName: "RegisterStream",
			Handler:    _Api_RegisterStream_Handler,
		},
		{
			MethodName: "UnregisterStream",
			Handler:    _Api_UnregisterStream_Handler,
		},
		{
			MethodName: "GetStreamInfo",
			Handler:    _Api_GetStreamInfo_Handler,
		},
		{
			MethodName: "GetClusterStreams",
			Handler:    _Api_GetClusterStreams_Handler,
		},
		{
			MethodName: "GetOptimalNodeForPublisher",
			Handler:    _Api_GetOptimalNodeForPublisher_Handler,
		},
		{
			MethodName: "GetOptimalNodeForSubscriber",
			Handler:    _Api_GetOptimalNodeForSubscriber_Handler,
		},
		{
			MethodName: "UpdateStreamState",
			Handler:    _Api_UpdateStreamState_Handler,
		},
		{
			MethodName: "SyncStreams",
			Handler:    _Api_SyncStreams_Handler,
		},
		{
			MethodName: "RemoveStream",
			Handler:    _Api_RemoveStream_Handler,
		},
		{
			MethodName: "RequestFullSync",
			Handler:    _Api_RequestFullSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
