// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点信息
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`     // manager, edge, worker, transcoder
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, offline
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // Unix timestamp in milliseconds
	StreamCount   int32                  `protobuf:"varint,7,opt,name=stream_count,json=streamCount,proto3" json:"stream_count,omitempty"`
	// 资源容量
	Capacity *ResourceCapacity `protobuf:"bytes,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// 当前资源使用情况
	CurrentLoad *ResourceUsage `protobuf:"bytes,9,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	// 节点元数据
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *NodeInfo) GetStreamCount() int32 {
	if x != nil {
		return x.StreamCount
	}
	return 0
}

func (x *NodeInfo) GetCapacity() *ResourceCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeInfo) GetCurrentLoad() *ResourceUsage {
	if x != nil {
		return x.CurrentLoad
	}
	return nil
}

func (x *NodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 资源容量配置
type ResourceCapacity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrentStreams int32                  `protobuf:"varint,1,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	MaxBandwidthMbps     float64                `protobuf:"fixed64,2,opt,name=max_bandwidth_mbps,json=maxBandwidthMbps,proto3" json:"max_bandwidth_mbps,omitempty"`
	MaxCpuPercent        float64                `protobuf:"fixed64,3,opt,name=max_cpu_percent,json=maxCpuPercent,proto3" json:"max_cpu_percent,omitempty"`
	MaxMemoryGb          float64                `protobuf:"fixed64,4,opt,name=max_memory_gb,json=maxMemoryGb,proto3" json:"max_memory_gb,omitempty"`
	MaxTranscodingSlots  int32                  `protobuf:"varint,5,opt,name=max_transcoding_slots,json=maxTranscodingSlots,proto3" json:"max_transcoding_slots,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceCapacity) Reset() {
	*x = ResourceCapacity{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapacity) ProtoMessage() {}

func (x *ResourceCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapacity.ProtoReflect.Descriptor instead.
func (*ResourceCapacity) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceCapacity) GetMaxConcurrentStreams() int32 {
	if x != nil {
		return x.MaxConcurrentStreams
	}
	return 0
}

func (x *ResourceCapacity) GetMaxBandwidthMbps() float64 {
	if x != nil {
		return x.MaxBandwidthMbps
	}
	return 0
}

func (x *ResourceCapacity) GetMaxCpuPercent() float64 {
	if x != nil {
		return x.MaxCpuPercent
	}
	return 0
}

func (x *ResourceCapacity) GetMaxMemoryGb() float64 {
	if x != nil {
		return x.MaxMemoryGb
	}
	return 0
}

func (x *ResourceCapacity) GetMaxTranscodingSlots() int32 {
	if x != nil {
		return x.MaxTranscodingSlots
	}
	return 0
}

// 资源使用情况
type ResourceUsage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent             float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryGb               float64                `protobuf:"fixed64,2,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	BandwidthMbps          float64                `protobuf:"fixed64,3,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	ConcurrentStreams      int32                  `protobuf:"varint,4,opt,name=concurrent_streams,json=concurrentStreams,proto3" json:"concurrent_streams,omitempty"`
	ActiveTranscodingTasks int32                  `protobuf:"varint,5,opt,name=active_transcoding_tasks,json=activeTranscodingTasks,proto3" json:"active_transcoding_tasks,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryGb() float64 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *ResourceUsage) GetBandwidthMbps() float64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *ResourceUsage) GetConcurrentStreams() int32 {
	if x != nil {
		return x.ConcurrentStreams
	}
	return 0
}

func (x *ResourceUsage) GetActiveTranscodingTasks() int32 {
	if x != nil {
		return x.ActiveTranscodingTasks
	}
	return 0
}

// 流信息
type StreamInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamPath      string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	PublisherNodeId string                 `protobuf:"bytes,2,opt,name=publisher_node_id,json=publisherNodeId,proto3" json:"publisher_node_id,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // active, inactive
	BandwidthMbps   float64                `protobuf:"fixed64,4,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	Codec           string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	Resolution      string                 `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Fps             float64                `protobuf:"fixed64,7,opt,name=fps,proto3" json:"fps,omitempty"`
	// 矢量时钟，用于冲突解决
	VectorClock map[string]uint64 `protobuf:"bytes,8,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 流已复制到的节点列表
	ReplicatedTo []string `protobuf:"bytes,9,rep,name=replicated_to,json=replicatedTo,proto3" json:"replicated_to,omitempty"`
	// 当前订阅者计数
	SubscriberCount int32 `protobuf:"varint,10,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	// 流的元数据
	Metadata      map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfo) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *StreamInfo) GetPublisherNodeId() string {
	if x != nil {
		return x.PublisherNodeId
	}
	return ""
}

func (x *StreamInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StreamInfo) GetBandwidthMbps() float64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *StreamInfo) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *StreamInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *StreamInfo) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *StreamInfo) GetVectorClock() map[string]uint64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *StreamInfo) GetReplicatedTo() []string {
	if x != nil {
		return x.ReplicatedTo
	}
	return nil
}

func (x *StreamInfo) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *StreamInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 健康状态报告
type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ResourceUsage *ResourceUsage         `protobuf:"bytes,2,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	ActiveStreams []string               `protobuf:"bytes,4,rep,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	LatencyMs     map[string]float64     `protobuf:"bytes,5,rep,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 与其他节点的延迟
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *HealthReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthReport) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *HealthReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthReport) GetActiveStreams() []string {
	if x != nil {
		return x.ActiveStreams
	}
	return nil
}

func (x *HealthReport) GetLatencyMs() map[string]float64 {
	if x != nil {
		return x.LatencyMs
	}
	return nil
}

// 同步响应
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedItems int32                  `protobuf:"varint,3,opt,name=affected_items,json=affectedItems,proto3" json:"affected_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetAffectedItems() int32 {
	if x != nil {
		return x.AffectedItems
	}
	return 0
}

// 流动态信息
type StreamDynamicInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BandwidthMbps   float64                `protobuf:"fixed64,1,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`      // 带宽使用 (Mbps)
	Fps             float64                `protobuf:"fixed64,2,opt,name=fps,proto3" json:"fps,omitempty"`                                               // 帧率
	SubscriberCount int32                  `protobuf:"varint,3,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"` // 订阅者数量
	LastUpdated     int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`             // 最后更新时间 (Unix timestamp in milliseconds)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamDynamicInfo) Reset() {
	*x = StreamDynamicInfo{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDynamicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDynamicInfo) ProtoMessage() {}

func (x *StreamDynamicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDynamicInfo.ProtoReflect.Descriptor instead.
func (*StreamDynamicInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *StreamDynamicInfo) GetBandwidthMbps() float64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *StreamDynamicInfo) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *StreamDynamicInfo) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *StreamDynamicInfo) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

// 流更新信息
type StreamUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	DynamicInfo   *StreamDynamicInfo     `protobuf:"bytes,2,opt,name=dynamic_info,json=dynamicInfo,proto3" json:"dynamic_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUpdate) Reset() {
	*x = StreamUpdate{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdate) ProtoMessage() {}

func (x *StreamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdate.ProtoReflect.Descriptor instead.
func (*StreamUpdate) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *StreamUpdate) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *StreamUpdate) GetDynamicInfo() *StreamDynamicInfo {
	if x != nil {
		return x.DynamicInfo
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x02pb\"\x9f\x03\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\x03R\rlastHeartbeat\x12!\n" +
	"\fstream_count\x18\a \x01(\x05R\vstreamCount\x120\n" +
	"\bcapacity\x18\b \x01(\v2\x14.pb.ResourceCapacityR\bcapacity\x124\n" +
	"\fcurrent_load\x18\t \x01(\v2\x11.pb.ResourceUsageR\vcurrentLoad\x126\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1a.pb.NodeInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x10ResourceCapacity\x124\n" +
	"\x16max_concurrent_streams\x18\x01 \x01(\x05R\x14maxConcurrentStreams\x12,\n" +
	"\x12max_bandwidth_mbps\x18\x02 \x01(\x01R\x10maxBandwidthMbps\x12&\n" +
	"\x0fmax_cpu_percent\x18\x03 \x01(\x01R\rmaxCpuPercent\x12\"\n" +
	"\rmax_memory_gb\x18\x04 \x01(\x01R\vmaxMemoryGb\x122\n" +
	"\x15max_transcoding_slots\x18\x05 \x01(\x05R\x13maxTranscodingSlots\"\xdd\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_gb\x18\x02 \x01(\x01R\bmemoryGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x03 \x01(\x01R\rbandwidthMbps\x12-\n" +
	"\x12concurrent_streams\x18\x04 \x01(\x05R\x11concurrentStreams\x128\n" +
	"\x18active_transcoding_tasks\x18\x05 \x01(\x05R\x16activeTranscodingTasks\"\xa9\x04\n" +
	"\n" +
	"StreamInfo\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12*\n" +
	"\x11publisher_node_id\x18\x02 \x01(\tR\x0fpublisherNodeId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12%\n" +
	"\x0ebandwidth_mbps\x18\x04 \x01(\x01R\rbandwidthMbps\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12\x1e\n" +
	"\n" +
	"resolution\x18\x06 \x01(\tR\n" +
	"resolution\x12\x10\n" +
	"\x03fps\x18\a \x01(\x01R\x03fps\x12B\n" +
	"\fvector_clock\x18\b \x03(\v2\x1f.pb.StreamInfo.VectorClockEntryR\vvectorClock\x12#\n" +
	"\rreplicated_to\x18\t \x03(\tR\freplicatedTo\x12)\n" +
	"\x10subscriber_count\x18\n" +
	" \x01(\x05R\x0fsubscriberCount\x128\n" +
	"\bmetadata\x18\v \x03(\v2\x1c.pb.StreamInfo.MetadataEntryR\bmetadata\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\fHealthReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\x0eresource_usage\x18\x02 \x01(\v2\x11.pb.ResourceUsageR\rresourceUsage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0eactive_streams\x18\x04 \x03(\tR\ractiveStreams\x12>\n" +
	"\n" +
	"latency_ms\x18\x05 \x03(\v2\x1f.pb.HealthReport.LatencyMsEntryR\tlatencyMs\x1a<\n" +
	"\x0eLatencyMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"i\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaffected_items\x18\x03 \x01(\x05R\raffectedItems\"\x9a\x01\n" +
	"\x11StreamDynamicInfo\x12%\n" +
	"\x0ebandwidth_mbps\x18\x01 \x01(\x01R\rbandwidthMbps\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x01R\x03fps\x12)\n" +
	"\x10subscriber_count\x18\x03 \x01(\x05R\x0fsubscriberCount\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated\"i\n" +
	"\fStreamUpdate\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x128\n" +
	"\fdynamic_info\x18\x02 \x01(\v2\x15.pb.StreamDynamicInfoR\vdynamicInfoB\x1fZ\x1dm7s.live/v5/plugin/cluster/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_common_proto_goTypes = []any{
	(*NodeInfo)(nil),          // 0: pb.NodeInfo
	(*ResourceCapacity)(nil),  // 1: pb.ResourceCapacity
	(*ResourceUsage)(nil),     // 2: pb.ResourceUsage
	(*StreamInfo)(nil),        // 3: pb.StreamInfo
	(*HealthReport)(nil),      // 4: pb.HealthReport
	(*SyncResponse)(nil),      // 5: pb.SyncResponse
	(*StreamDynamicInfo)(nil), // 6: pb.StreamDynamicInfo
	(*StreamUpdate)(nil),      // 7: pb.StreamUpdate
	nil,                       // 8: pb.NodeInfo.MetadataEntry
	nil,                       // 9: pb.StreamInfo.VectorClockEntry
	nil,                       // 10: pb.StreamInfo.MetadataEntry
	nil,                       // 11: pb.HealthReport.LatencyMsEntry
}
var file_common_proto_depIdxs = []int32{
	1,  // 0: pb.NodeInfo.capacity:type_name -> pb.ResourceCapacity
	2,  // 1: pb.NodeInfo.current_load:type_name -> pb.ResourceUsage
	8,  // 2: pb.NodeInfo.metadata:type_name -> pb.NodeInfo.MetadataEntry
	9,  // 3: pb.StreamInfo.vector_clock:type_name -> pb.StreamInfo.VectorClockEntry
	10, // 4: pb.StreamInfo.metadata:type_name -> pb.StreamInfo.MetadataEntry
	2,  // 5: pb.HealthReport.resource_usage:type_name -> pb.ResourceUsage
	11, // 6: pb.HealthReport.latency_ms:type_name -> pb.HealthReport.LatencyMsEntry
	6,  // 7: pb.StreamUpdate.dynamic_info:type_name -> pb.StreamDynamicInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
