// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册流请求
type RegisterStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamInfo    *StreamInfo            `protobuf:"bytes,1,opt,name=stream_info,json=streamInfo,proto3" json:"stream_info,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStreamRequest) Reset() {
	*x = RegisterStreamRequest{}
	mi := &file_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStreamRequest) ProtoMessage() {}

func (x *RegisterStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStreamRequest.ProtoReflect.Descriptor instead.
func (*RegisterStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterStreamRequest) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

func (x *RegisterStreamRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 注册流响应数据
type RegisterStreamResponseData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConflictDetected bool                   `protobuf:"varint,1,opt,name=conflict_detected,json=conflictDetected,proto3" json:"conflict_detected,omitempty"`
	ResolvedStream   *StreamInfo            `protobuf:"bytes,2,opt,name=resolved_stream,json=resolvedStream,proto3" json:"resolved_stream,omitempty"` // 如果检测到冲突，返回解决后的流信息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterStreamResponseData) Reset() {
	*x = RegisterStreamResponseData{}
	mi := &file_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStreamResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStreamResponseData) ProtoMessage() {}

func (x *RegisterStreamResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStreamResponseData.ProtoReflect.Descriptor instead.
func (*RegisterStreamResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterStreamResponseData) GetConflictDetected() bool {
	if x != nil {
		return x.ConflictDetected
	}
	return false
}

func (x *RegisterStreamResponseData) GetResolvedStream() *StreamInfo {
	if x != nil {
		return x.ResolvedStream
	}
	return nil
}

// 注册流响应
type RegisterStreamResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RegisterStreamResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStreamResponse) Reset() {
	*x = RegisterStreamResponse{}
	mi := &file_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStreamResponse) ProtoMessage() {}

func (x *RegisterStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStreamResponse.ProtoReflect.Descriptor instead.
func (*RegisterStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterStreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterStreamResponse) GetData() *RegisterStreamResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 注销流请求
type UnregisterStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterStreamRequest) Reset() {
	*x = UnregisterStreamRequest{}
	mi := &file_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterStreamRequest) ProtoMessage() {}

func (x *UnregisterStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterStreamRequest.ProtoReflect.Descriptor instead.
func (*UnregisterStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterStreamRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *UnregisterStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UnregisterStreamRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 注销流响应数据
type UnregisterStreamResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterStreamResponseData) Reset() {
	*x = UnregisterStreamResponseData{}
	mi := &file_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterStreamResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterStreamResponseData) ProtoMessage() {}

func (x *UnregisterStreamResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterStreamResponseData.ProtoReflect.Descriptor instead.
func (*UnregisterStreamResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterStreamResponseData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 注销流响应
type UnregisterStreamResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UnregisterStreamResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterStreamResponse) Reset() {
	*x = UnregisterStreamResponse{}
	mi := &file_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterStreamResponse) ProtoMessage() {}

func (x *UnregisterStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterStreamResponse.ProtoReflect.Descriptor instead.
func (*UnregisterStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterStreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnregisterStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnregisterStreamResponse) GetData() *UnregisterStreamResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取流信息请求
type GetStreamInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoRequest) Reset() {
	*x = GetStreamInfoRequest{}
	mi := &file_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoRequest) ProtoMessage() {}

func (x *GetStreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{6}
}

func (x *GetStreamInfoRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

// 获取流信息响应数据
type GetStreamInfoResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamInfo    *StreamInfo            `protobuf:"bytes,1,opt,name=stream_info,json=streamInfo,proto3" json:"stream_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoResponseData) Reset() {
	*x = GetStreamInfoResponseData{}
	mi := &file_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoResponseData) ProtoMessage() {}

func (x *GetStreamInfoResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoResponseData.ProtoReflect.Descriptor instead.
func (*GetStreamInfoResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{7}
}

func (x *GetStreamInfoResponseData) GetStreamInfo() *StreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

// 获取流信息响应
type GetStreamInfoResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetStreamInfoResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoResponse) Reset() {
	*x = GetStreamInfoResponse{}
	mi := &file_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoResponse) ProtoMessage() {}

func (x *GetStreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{8}
}

func (x *GetStreamInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetStreamInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStreamInfoResponse) GetData() *GetStreamInfoResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取集群流列表请求
type GetClusterStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeFilter    string                 `protobuf:"bytes,1,opt,name=node_filter,json=nodeFilter,proto3" json:"node_filter,omitempty"`    // 可选，按节点筛选
	StateFilter   string                 `protobuf:"bytes,2,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"` // 可选，按状态筛选
	PathPrefix    string                 `protobuf:"bytes,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`    // 可选，按路径前缀筛选
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                               // 可选，限制返回数量
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                             // 可选，分页偏移
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStreamsRequest) Reset() {
	*x = GetClusterStreamsRequest{}
	mi := &file_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStreamsRequest) ProtoMessage() {}

func (x *GetClusterStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStreamsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStreamsRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{9}
}

func (x *GetClusterStreamsRequest) GetNodeFilter() string {
	if x != nil {
		return x.NodeFilter
	}
	return ""
}

func (x *GetClusterStreamsRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

func (x *GetClusterStreamsRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *GetClusterStreamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetClusterStreamsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 获取集群流列表响应数据
type GetClusterStreamsResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamInfo          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数，用于分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStreamsResponseData) Reset() {
	*x = GetClusterStreamsResponseData{}
	mi := &file_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStreamsResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStreamsResponseData) ProtoMessage() {}

func (x *GetClusterStreamsResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStreamsResponseData.ProtoReflect.Descriptor instead.
func (*GetClusterStreamsResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{10}
}

func (x *GetClusterStreamsResponseData) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *GetClusterStreamsResponseData) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取集群流列表响应
type GetClusterStreamsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetClusterStreamsResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStreamsResponse) Reset() {
	*x = GetClusterStreamsResponse{}
	mi := &file_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStreamsResponse) ProtoMessage() {}

func (x *GetClusterStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStreamsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStreamsResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{11}
}

func (x *GetClusterStreamsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetClusterStreamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetClusterStreamsResponse) GetData() *GetClusterStreamsResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取发布者最优节点请求
type GetOptimalNodeForPublisherRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Region                 string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`                                                                   // 可选，首选区域
	Codec                  string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`                                                                     // 可选，编码信息
	EstimatedBandwidthMbps float64                `protobuf:"fixed64,3,opt,name=estimated_bandwidth_mbps,json=estimatedBandwidthMbps,proto3" json:"estimated_bandwidth_mbps,omitempty"` // 可选，预估带宽
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetOptimalNodeForPublisherRequest) Reset() {
	*x = GetOptimalNodeForPublisherRequest{}
	mi := &file_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForPublisherRequest) ProtoMessage() {}

func (x *GetOptimalNodeForPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForPublisherRequest.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForPublisherRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{12}
}

func (x *GetOptimalNodeForPublisherRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetOptimalNodeForPublisherRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *GetOptimalNodeForPublisherRequest) GetEstimatedBandwidthMbps() float64 {
	if x != nil {
		return x.EstimatedBandwidthMbps
	}
	return 0
}

// 获取发布者最优节点响应数据
type GetOptimalNodeForPublisherResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptimalNode   *NodeInfo              `protobuf:"bytes,1,opt,name=optimal_node,json=optimalNode,proto3" json:"optimal_node,omitempty"`
	FallbackNodes []*NodeInfo            `protobuf:"bytes,2,rep,name=fallback_nodes,json=fallbackNodes,proto3" json:"fallback_nodes,omitempty"` // 备选节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptimalNodeForPublisherResponseData) Reset() {
	*x = GetOptimalNodeForPublisherResponseData{}
	mi := &file_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForPublisherResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForPublisherResponseData) ProtoMessage() {}

func (x *GetOptimalNodeForPublisherResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForPublisherResponseData.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForPublisherResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{13}
}

func (x *GetOptimalNodeForPublisherResponseData) GetOptimalNode() *NodeInfo {
	if x != nil {
		return x.OptimalNode
	}
	return nil
}

func (x *GetOptimalNodeForPublisherResponseData) GetFallbackNodes() []*NodeInfo {
	if x != nil {
		return x.FallbackNodes
	}
	return nil
}

// 获取发布者最优节点响应
type GetOptimalNodeForPublisherResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Code          int32                                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetOptimalNodeForPublisherResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptimalNodeForPublisherResponse) Reset() {
	*x = GetOptimalNodeForPublisherResponse{}
	mi := &file_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForPublisherResponse) ProtoMessage() {}

func (x *GetOptimalNodeForPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForPublisherResponse.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForPublisherResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{14}
}

func (x *GetOptimalNodeForPublisherResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOptimalNodeForPublisherResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOptimalNodeForPublisherResponse) GetData() *GetOptimalNodeForPublisherResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取订阅者最优节点请求
type GetOptimalNodeForSubscriberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	SubscriberIp  string                 `protobuf:"bytes,2,opt,name=subscriber_ip,json=subscriberIp,proto3" json:"subscriber_ip,omitempty"` // 可选，订阅者 IP，用于地理位置优化
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                                 // 可选，首选区域
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptimalNodeForSubscriberRequest) Reset() {
	*x = GetOptimalNodeForSubscriberRequest{}
	mi := &file_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForSubscriberRequest) ProtoMessage() {}

func (x *GetOptimalNodeForSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForSubscriberRequest.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{15}
}

func (x *GetOptimalNodeForSubscriberRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *GetOptimalNodeForSubscriberRequest) GetSubscriberIp() string {
	if x != nil {
		return x.SubscriberIp
	}
	return ""
}

func (x *GetOptimalNodeForSubscriberRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// 获取订阅者最优节点响应数据
type GetOptimalNodeForSubscriberResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptimalNode   *NodeInfo              `protobuf:"bytes,1,opt,name=optimal_node,json=optimalNode,proto3" json:"optimal_node,omitempty"`
	FallbackNodes []*NodeInfo            `protobuf:"bytes,2,rep,name=fallback_nodes,json=fallbackNodes,proto3" json:"fallback_nodes,omitempty"` // 备选节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptimalNodeForSubscriberResponseData) Reset() {
	*x = GetOptimalNodeForSubscriberResponseData{}
	mi := &file_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForSubscriberResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForSubscriberResponseData) ProtoMessage() {}

func (x *GetOptimalNodeForSubscriberResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForSubscriberResponseData.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForSubscriberResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{16}
}

func (x *GetOptimalNodeForSubscriberResponseData) GetOptimalNode() *NodeInfo {
	if x != nil {
		return x.OptimalNode
	}
	return nil
}

func (x *GetOptimalNodeForSubscriberResponseData) GetFallbackNodes() []*NodeInfo {
	if x != nil {
		return x.FallbackNodes
	}
	return nil
}

// 获取订阅者最优节点响应
type GetOptimalNodeForSubscriberResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Code          int32                                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetOptimalNodeForSubscriberResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptimalNodeForSubscriberResponse) Reset() {
	*x = GetOptimalNodeForSubscriberResponse{}
	mi := &file_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptimalNodeForSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptimalNodeForSubscriberResponse) ProtoMessage() {}

func (x *GetOptimalNodeForSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptimalNodeForSubscriberResponse.ProtoReflect.Descriptor instead.
func (*GetOptimalNodeForSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{17}
}

func (x *GetOptimalNodeForSubscriberResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOptimalNodeForSubscriberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOptimalNodeForSubscriberResponse) GetData() *GetOptimalNodeForSubscriberResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新流状态请求
type UpdateStreamStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamStateRequest) Reset() {
	*x = UpdateStreamStateRequest{}
	mi := &file_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamStateRequest) ProtoMessage() {}

func (x *UpdateStreamStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateStreamStateRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStreamStateRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *UpdateStreamStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateStreamStateRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 更新流状态响应数据
type UpdateStreamStateResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamStateResponseData) Reset() {
	*x = UpdateStreamStateResponseData{}
	mi := &file_stream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamStateResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamStateResponseData) ProtoMessage() {}

func (x *UpdateStreamStateResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamStateResponseData.ProtoReflect.Descriptor instead.
func (*UpdateStreamStateResponseData) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateStreamStateResponseData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 更新流状态响应
type UpdateStreamStateResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UpdateStreamStateResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamStateResponse) Reset() {
	*x = UpdateStreamStateResponse{}
	mi := &file_stream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamStateResponse) ProtoMessage() {}

func (x *UpdateStreamStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateStreamStateResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateStreamStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateStreamStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateStreamStateResponse) GetData() *UpdateStreamStateResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stream_proto protoreflect.FileDescriptor

const file_stream_proto_rawDesc = "" +
	"\n" +
	"\fstream.proto\x12\x02pb\x1a\fcommon.proto\"g\n" +
	"\x15RegisterStreamRequest\x12/\n" +
	"\vstream_info\x18\x01 \x01(\v2\x0e.pb.StreamInfoR\n" +
	"streamInfo\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\x82\x01\n" +
	"\x1aRegisterStreamResponseData\x12+\n" +
	"\x11conflict_detected\x18\x01 \x01(\bR\x10conflictDetected\x127\n" +
	"\x0fresolved_stream\x18\x02 \x01(\v2\x0e.pb.StreamInfoR\x0eresolvedStream\"z\n" +
	"\x16RegisterStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.pb.RegisterStreamResponseDataR\x04data\"r\n" +
	"\x17UnregisterStreamRequest\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"8\n" +
	"\x1cUnregisterStreamResponseData\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"~\n" +
	"\x18UnregisterStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x01(\v2 .pb.UnregisterStreamResponseDataR\x04data\"7\n" +
	"\x14GetStreamInfoRequest\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\"L\n" +
	"\x19GetStreamInfoResponseData\x12/\n" +
	"\vstream_info\x18\x01 \x01(\v2\x0e.pb.StreamInfoR\n" +
	"streamInfo\"x\n" +
	"\x15GetStreamInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.GetStreamInfoResponseDataR\x04data\"\xad\x01\n" +
	"\x18GetClusterStreamsRequest\x12\x1f\n" +
	"\vnode_filter\x18\x01 \x01(\tR\n" +
	"nodeFilter\x12!\n" +
	"\fstate_filter\x18\x02 \x01(\tR\vstateFilter\x12\x1f\n" +
	"\vpath_prefix\x18\x03 \x01(\tR\n" +
	"pathPrefix\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"j\n" +
	"\x1dGetClusterStreamsResponseData\x12(\n" +
	"\astreams\x18\x01 \x03(\v2\x0e.pb.StreamInfoR\astreams\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x80\x01\n" +
	"\x19GetClusterStreamsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2!.pb.GetClusterStreamsResponseDataR\x04data\"\x8b\x01\n" +
	"!GetOptimalNodeForPublisherRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x128\n" +
	"\x18estimated_bandwidth_mbps\x18\x03 \x01(\x01R\x16estimatedBandwidthMbps\"\x8e\x01\n" +
	"&GetOptimalNodeForPublisherResponseData\x12/\n" +
	"\foptimal_node\x18\x01 \x01(\v2\f.pb.NodeInfoR\voptimalNode\x123\n" +
	"\x0efallback_nodes\x18\x02 \x03(\v2\f.pb.NodeInfoR\rfallbackNodes\"\x92\x01\n" +
	"\"GetOptimalNodeForPublisherResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x01(\v2*.pb.GetOptimalNodeForPublisherResponseDataR\x04data\"\x82\x01\n" +
	"\"GetOptimalNodeForSubscriberRequest\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12#\n" +
	"\rsubscriber_ip\x18\x02 \x01(\tR\fsubscriberIp\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x8f\x01\n" +
	"'GetOptimalNodeForSubscriberResponseData\x12/\n" +
	"\foptimal_node\x18\x01 \x01(\v2\f.pb.NodeInfoR\voptimalNode\x123\n" +
	"\x0efallback_nodes\x18\x02 \x03(\v2\f.pb.NodeInfoR\rfallbackNodes\"\x94\x01\n" +
	"#GetOptimalNodeForSubscriberResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x04data\x18\x03 \x01(\v2+.pb.GetOptimalNodeForSubscriberResponseDataR\x04data\"p\n" +
	"\x18UpdateStreamStateRequest\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"9\n" +
	"\x1dUpdateStreamStateResponseData\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x80\x01\n" +
	"\x19UpdateStreamStateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2!.pb.UpdateStreamStateResponseDataR\x04dataB\x1fZ\x1dm7s.live/v5/plugin/cluster/pbb\x06proto3"

var (
	file_stream_proto_rawDescOnce sync.Once
	file_stream_proto_rawDescData []byte
)

func file_stream_proto_rawDescGZIP() []byte {
	file_stream_proto_rawDescOnce.Do(func() {
		file_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)))
	})
	return file_stream_proto_rawDescData
}

var file_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_stream_proto_goTypes = []any{
	(*RegisterStreamRequest)(nil),                   // 0: pb.RegisterStreamRequest
	(*RegisterStreamResponseData)(nil),              // 1: pb.RegisterStreamResponseData
	(*RegisterStreamResponse)(nil),                  // 2: pb.RegisterStreamResponse
	(*UnregisterStreamRequest)(nil),                 // 3: pb.UnregisterStreamRequest
	(*UnregisterStreamResponseData)(nil),            // 4: pb.UnregisterStreamResponseData
	(*UnregisterStreamResponse)(nil),                // 5: pb.UnregisterStreamResponse
	(*GetStreamInfoRequest)(nil),                    // 6: pb.GetStreamInfoRequest
	(*GetStreamInfoResponseData)(nil),               // 7: pb.GetStreamInfoResponseData
	(*GetStreamInfoResponse)(nil),                   // 8: pb.GetStreamInfoResponse
	(*GetClusterStreamsRequest)(nil),                // 9: pb.GetClusterStreamsRequest
	(*GetClusterStreamsResponseData)(nil),           // 10: pb.GetClusterStreamsResponseData
	(*GetClusterStreamsResponse)(nil),               // 11: pb.GetClusterStreamsResponse
	(*GetOptimalNodeForPublisherRequest)(nil),       // 12: pb.GetOptimalNodeForPublisherRequest
	(*GetOptimalNodeForPublisherResponseData)(nil),  // 13: pb.GetOptimalNodeForPublisherResponseData
	(*GetOptimalNodeForPublisherResponse)(nil),      // 14: pb.GetOptimalNodeForPublisherResponse
	(*GetOptimalNodeForSubscriberRequest)(nil),      // 15: pb.GetOptimalNodeForSubscriberRequest
	(*GetOptimalNodeForSubscriberResponseData)(nil), // 16: pb.GetOptimalNodeForSubscriberResponseData
	(*GetOptimalNodeForSubscriberResponse)(nil),     // 17: pb.GetOptimalNodeForSubscriberResponse
	(*UpdateStreamStateRequest)(nil),                // 18: pb.UpdateStreamStateRequest
	(*UpdateStreamStateResponseData)(nil),           // 19: pb.UpdateStreamStateResponseData
	(*UpdateStreamStateResponse)(nil),               // 20: pb.UpdateStreamStateResponse
	(*StreamInfo)(nil),                              // 21: pb.StreamInfo
	(*NodeInfo)(nil),                                // 22: pb.NodeInfo
}
var file_stream_proto_depIdxs = []int32{
	21, // 0: pb.RegisterStreamRequest.stream_info:type_name -> pb.StreamInfo
	21, // 1: pb.RegisterStreamResponseData.resolved_stream:type_name -> pb.StreamInfo
	1,  // 2: pb.RegisterStreamResponse.data:type_name -> pb.RegisterStreamResponseData
	4,  // 3: pb.UnregisterStreamResponse.data:type_name -> pb.UnregisterStreamResponseData
	21, // 4: pb.GetStreamInfoResponseData.stream_info:type_name -> pb.StreamInfo
	7,  // 5: pb.GetStreamInfoResponse.data:type_name -> pb.GetStreamInfoResponseData
	21, // 6: pb.GetClusterStreamsResponseData.streams:type_name -> pb.StreamInfo
	10, // 7: pb.GetClusterStreamsResponse.data:type_name -> pb.GetClusterStreamsResponseData
	22, // 8: pb.GetOptimalNodeForPublisherResponseData.optimal_node:type_name -> pb.NodeInfo
	22, // 9: pb.GetOptimalNodeForPublisherResponseData.fallback_nodes:type_name -> pb.NodeInfo
	13, // 10: pb.GetOptimalNodeForPublisherResponse.data:type_name -> pb.GetOptimalNodeForPublisherResponseData
	22, // 11: pb.GetOptimalNodeForSubscriberResponseData.optimal_node:type_name -> pb.NodeInfo
	22, // 12: pb.GetOptimalNodeForSubscriberResponseData.fallback_nodes:type_name -> pb.NodeInfo
	16, // 13: pb.GetOptimalNodeForSubscriberResponse.data:type_name -> pb.GetOptimalNodeForSubscriberResponseData
	19, // 14: pb.UpdateStreamStateResponse.data:type_name -> pb.UpdateStreamStateResponseData
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_stream_proto_init() }
func file_stream_proto_init() {
	if File_stream_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_proto_goTypes,
		DependencyIndexes: file_stream_proto_depIdxs,
		MessageInfos:      file_stream_proto_msgTypes,
	}.Build()
	File_stream_proto = out.File
	file_stream_proto_goTypes = nil
	file_stream_proto_depIdxs = nil
}
